extends: default
ignore: |
  node_modules/*
  content/images/*
  web/game/assets/*
  playwright-report/*
  **/*.spdx.json
rules:
  max: 140
  level: warning
  line-length: disable        # (optional) ignore long lines
  document-start: disable      # no warning about missing '---'
    # indentation:
    #   level: warning           # example: downgrade indentation to warning
  indentation:
    indent-sequences: false
  truthy: disable # no warning about "on/off/yes/n
