extends: default
ignore: |
  node_modules/*
  content/images/*
  web/game/assets/*
  playwright-report/*
  **/*.spdx.json
rules:
  document-start: disable      # no warning about missing '---'
  truthy: disable              # no warning about "on/off/yes/n
  line-length:
    max: 200
    level: warning             # warn only, do not fail the job
  indentation:
    indent-sequences: false
    #    level: warning        # example: downgrade indentation to warning
